### ISSUE TITLE
Styles for the new password strength meter

### ISSUE THREAD

**Issue by claudiosmweb** [woothemes/storefront#245]
Now we have a password strength meter and this need styles on storefront:
https://github.com/woothemes/woocommerce/pull/9319

In core we use:

```scss
	/**
	 *  Password strength meter
	 */
	.woocommerce-password-strength {
		text-align: center;
		font-weight: 600;
		padding: 3px 0px 3px 0px;

		&.strong {
			background-color: #c1e1b9;
			border-color: #83c373;
		}

		&.short {
			background-color: #f1adad;
			border-color: #e35b5b;
		}

		&.bad {
			background-color: #fbc5a9;
			border-color: #f78b53;
		}

		&.good {
			background-color: #ffe399;
			border-color: #ffc733;
		}
	}
```
