### ISSUE TITLE
Using susy mixins for media queries

### ISSUE THREAD

**Issue by montalvomiguelo** [woothemes/storefront#283]
Susy has built-in media-query handling... so we don't need to write full media directive every time:

` susy-breakpoint($query, $layout, $no-query)`
`susy-media($query, $no-query)`

And maybe it could be easier to read/maintain if we keep them local to the component:

```scss
/**
 * General Layout
 */

.col-full {
	margin-left: 1.387em;
	margin-right: 1.387em;

	@include susy-media(569px) {
		margin-left: 2.618em;
		margin-right: 2.618em;
	}

	@include susy-media(768px) {
		@include clearfix;
	}

	@include susy-media(1043px) {
		@include container(65.141em);
	}

}
```
