### ISSUE TITLE
simple cart count correction for rtl languages

### ISSUE THREAD

**Issue by mostafazs** [woothemes/storefront#323]
Hi
i found not just a bug...just a bad positioning of cart on rtl languages 
It's better that class="count" , that show number of products usee choose on basket , float to right ..it's better for right to left languages
then i add a simple css rule to count class
I just add 
```css
.count{
float:right;
}
```

**Comment by jameskoster** [comment]
Shouldn't it mirror the ltr version? Doesn't this look good? https://cloudup.com/cOxyUl_i8ni

**Comment by mostafazs** [comment]
don't think ...But i add mentioned css to rtl.css file ( on main storefront folder...don't exist i create this file ) 
Now it's look like [https://i.imgsafe.org/725b93b.png](https://i.imgsafe.org/725b93b.png)

And i don't think it mirror ltr version if we just add a ```css float:right ```
to `woocommerce-rtl.css` file at 
```css
.site-header-cart .cart-contents .count{
font-weight:400;
opacity:.5;
font-size:.857em;
float:right;
}
```

Also i think it's better that cart icon float to right ..but don't know how do that.
